# Generated by Django 4.1.7 on 2023-03-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0002_alter_task_isdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
