# Generated by Django 4.1.7 on 2023-03-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0005_alter_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
